### ISSUE TITLE
send_to_cloud.pyについて

### ISSUE THREAD

**Issue by umentu** [soracom/handson#29]
38-39行目のread_distance関数の定義

```
return distance
GPIO.cleanup()
```

ですが、return後にGPIO.cleanup()を書いても実行されないため、

```
GPIO.cleanup()
return distance
```

とすべきかと思われます。そうすることで9行目の

```
GPIO.setwarnings(False)
```

が不要になります。

**Comment by umentu** [comment]
あと追記ですが、

```
    GPIO.output(TRIG, GPIO.LOW)
    time.sleep(0.3)

    # TRIGに短いパルスを送る
    GPIO.output(TRIG, GPIO.HIGH)
    time.sleep(0.00001)
    GPIO.output(TRIG, GPIO.LOW)

```

よりも

```
    GPIO.output(self.trig_pin, GPIO.LOW)
    time.sleep(0.3)

    # TRIGに短いパルスを送る
    GPIO.output(self.trig_pin, True)
    time.sleep(0.0001)
    GPIO.output(self.trig_pin, False)
```

のほうが正確な距離が測れるかと思います。

**Comment by j3tm0t0** [comment]
フィードバックありがとうございます。

### GPIO.cleanup()について

ご指摘の通り、returnの上にないとコード上通らないので、修正いたします。
しかしながら、Ctrl+Cで止めた場合にループのどの場所で止まったかによっては、cleanupされずに次回実行時にwarningは出てしまうため、GPIO.setwarnings(False)は入れておこうと思います。

### トリガー時間について

トリガー時間を変えて計測してみました。データシート上は10マイクロ秒以上とありますが、トリガー時間を11マイクロ秒にしてみたところ、精度が少し上がりました(ただし、ノイズ的なばらつきは残る)。逆に100マイクロ秒にしてみたところ、またさらに精度が落ちたので、ひとまず11マイクロ秒としてみたいと思います。

[計測結果のグラフ](https://docs.google.com/spreadsheets/d/1arDpUNrCDJPPluqHtIyktpfzSe7B_xzWMdQeFxVJNaQ/pubchart?oid=502617513&format=interactive)
