### ISSUE TITLE
ハンズオン用テキスト について

### ISSUE THREAD

**Issue by umentu** [soracom/handson#32]
https://github.com/soracom/handson/blob/master/setup/setup.md の

```
sudo apt-get install -y usb-modeswitch wvdial
```

の前に、

```
sudo apt-get update
```

でパッケージリストの更新を行う必要があります。パッケージリストが古いため、インストールが行えませんでした。

**Comment by chiemit** [comment]
フィードバックありがとうございます！setup.mdを更新し、パッケージインストールの前に`sudo apt-get update`を実行するステップを追加しました。
